# Generated by Django 4.0.6 on 2022-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='patient_Bmi',
        ),
        migrations.AddField(
            model_name='vital',
            name='age',
            field=models.PositiveSmallIntegerField(default=20, null=True),
        ),
    ]
    
